name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version:
          - 18.x
          - 20.x
          - 22.x
        exclude:
          - runs-on: macos-latest
            node-version: 18.x
          - runs-on: macos-latest
            node-version: 20.x
          - runs-on: windows-latest
            node-version: 18.x
          - runs-on: windows-latest
            node-version: 20.x

    name: Build on node ${{ matrix.node-version }} ${{ matrix.runs-on }}

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test:ci
